# Generated by Django 2.2.5 on 2022-05-31 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
            ],
            options={
                'verbose_name': '攻击',
                'verbose_name_plural': '攻击',
            },
        ),
        migrations.CreateModel(
            name='Log_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='日志类型')),
            ],
            options={
                'verbose_name': '日志类型',
                'verbose_name_plural': '日志类型',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
            ],
            options={
                'verbose_name': '服务',
                'verbose_name_plural': '服务',
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('ip', models.CharField(max_length=50, verbose_name='ip')),
                ('os', models.CharField(max_length=50, verbose_name='os')),
                ('desc', models.TextField(verbose_name='描述')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1_admin.Service')),
            ],
            options={
                'verbose_name': '靶标',
                'verbose_name_plural': '靶标',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path1', models.CharField(max_length=50, verbose_name='路径')),
                ('path2', models.CharField(max_length=50, verbose_name='路径')),
                ('desc', models.TextField(verbose_name='描述')),
                ('log_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1_admin.Log_type', verbose_name='日志类型')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1_admin.Target', verbose_name='靶标')),
            ],
            options={
                'verbose_name': '日志',
                'verbose_name_plural': '日志',
            },
        ),
    ]
